<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.8.1" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.54" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\APNAPASHU.DataContract\APNAPASHU.DataContract.csproj" />
  </ItemGroup>

</Project>