<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entity\Buyer\**" />
    <Compile Remove="Entity\Seller\**" />
    <Compile Remove="Models\Web\Buyer\**" />
    <EmbeddedResource Remove="Entity\Buyer\**" />
    <EmbeddedResource Remove="Entity\Seller\**" />
    <EmbeddedResource Remove="Models\Web\Buyer\**" />
    <None Remove="Entity\Buyer\**" />
    <None Remove="Entity\Seller\**" />
    <None Remove="Models\Web\Buyer\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Mobile\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.0" />
  </ItemGroup>

</Project>